import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms and Conditions",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-canvas-cream font-sans text-ink-black py-16 px-6 md:px-12 lg:px-24">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/auth/signup"
          className="inline-flex items-center gap-2 text-slate-gray hover:text-signal-orange transition-colors mb-8 group">
          <ArrowLeft
            size={16}
            className="group-hover:-translate-x-1 transition-transform"
          />
          <span className="font-medium">Back to Sign Up</span>
        </Link>

        <h1 className="text-4xl md:text-5xl font-semibold tracking-mc-tight mb-4">
          Terms and Conditions
        </h1>
        <p className="text-slate-gray mb-12">Last updated: April 2026</p>

        <div className="space-y-8 text-lg leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              1. Introduction
            </h2>
            <p>
              Welcome to ContentPilot. By accessing or using our platform, you
              agree to be bound by these Terms and Conditions. ContentPilot
              provides an AI-powered content generation service that analyzes
              top search engine results for a given keyword and generates
              SEO-optimized blog content based on those insights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              2. Service Description
            </h2>
            <p>
              Our service allows users to input specific keywords. Our backend
              system then processes these keywords by analyzing the top 5 Google
              search results and their associated keywords. Utilizing this data,
              ContentPilot generates a tailored blog post that incorporates the
              target keywords to help improve your structural SEO and content
              strategy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              3. User Responsibilities
            </h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                You are responsible for the keywords you submit and the content
                generated using our platform.
              </li>
              <li>
                You agree not to use the service to generate illegal, harmful,
                or plagiarized content.
              </li>
              <li>
                While ContentPilot strives to produce highly optimized and
                relevant content, you are responsible for reviewing and
                verifying all generated content before publication.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              4. Intellectual Property
            </h2>
            <p>
              The content generated by ContentPilot based on your input keywords
              becomes your property upon creation. However, the underlying AI
              models, algorithms, search analysis techniques, and platform
              software remain the exclusive property of ContentPilot.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              5. Limitation of Liability
            </h2>
            <p>
              ContentPilot does not guarantee specific search engine rankings or
              traffic increases as a result of using the generated content. SEO
              is subject to external search engine algorithms that we do not
              control. ContentPilot is not liable for any direct, indirect, or
              consequential damages arising from the use of our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              6. Modifications to Service
            </h2>
            <p>
              We reserve the right to modify or discontinue, temporarily or
              permanently, the service (or any part thereof) with or without
              notice. We may also update these terms from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 tracking-mc-tight text-signal-orange">
              7. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a
                href="mailto:legal@contentpilot.ai"
                className="text-link-blue hover:underline">
                legal@contentpilot.ai
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
