"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  ScrollText,
  Compass,
  UserCog,
  Scale,
  ShieldAlert,
  RefreshCw,
  Mail,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

type Section = {
  icon: LucideIcon;
  tag: string;
  title: string;
  body: React.ReactNode;
};

const sections: Section[] = [
  {
    icon: ScrollText,
    tag: "Section 01",
    title: "Introduction",
    body: (
      <p>
        Welcome to ContentPilot. By accessing or using our platform, you agree
        to be bound by these Terms and Conditions. ContentPilot is an
        AI-assisted SEO content platform that analyzes top search results for
        a given keyword and produces a complete content package — a long-form
        Markdown article, SEO metadata, link ideas, and an FAQ shaped by real
        search intent.
      </p>
    ),
  },
  {
    icon: Compass,
    tag: "Section 02",
    title: "Service Description",
    body: (
      <p>
        Our service lets you submit a topic or keyword, choose a target
        language, and set a target word count from the dashboard. Our backend
        then analyzes the top Google search results and their associated
        keywords, and generates a tailored long-form article together with an
        SEO title and meta description, target keyword suggestions, internal
        and external link ideas, and an FAQ section based on search intent.
      </p>
    ),
  },
  {
    icon: UserCog,
    tag: "Section 03",
    title: "User Responsibilities",
    body: (
      <ul className="space-y-3">
        <li>
          You are responsible for the topics, keywords, and other inputs you
          submit, as well as the content ContentPilot generates from them.
        </li>
        <li>
          You agree not to use the service to generate illegal, harmful,
          infringing, or plagiarized content.
        </li>
        <li>
          While ContentPilot strives to produce highly optimized and relevant
          output, you are responsible for reviewing, editing, and verifying
          all generated articles, SEO metadata, link ideas, and FAQs before
          publication.
        </li>
      </ul>
    ),
  },
  {
    icon: Scale,
    tag: "Section 04",
    title: "Intellectual Property",
    body: (
      <p>
        The content generated by ContentPilot from your submitted inputs
        becomes your property upon creation. The underlying AI models,
        prompts, SERP analysis pipeline, platform software, and brand assets
        remain the exclusive property of ContentPilot and may not be copied,
        resold, or reverse-engineered.
      </p>
    ),
  },
  {
    icon: ShieldAlert,
    tag: "Section 05",
    title: "Limitation of Liability",
    body: (
      <p>
        ContentPilot does not guarantee any specific search engine ranking,
        traffic, or revenue outcome as a result of using the generated
        content. SEO results depend on external search engine algorithms that
        we do not control. ContentPilot is not liable for any direct,
        indirect, incidental, or consequential damages arising from the use
        of our service.
      </p>
    ),
  },
  {
    icon: RefreshCw,
    tag: "Section 06",
    title: "Modifications to the Service",
    body: (
      <p>
        We reserve the right to modify, suspend, or discontinue any part of
        the service at any time, with or without notice. We may also update
        these Terms from time to time. Continued use of the platform after an
        update means you accept the revised Terms.
      </p>
    ),
  },
  {
    icon: Mail,
    tag: "Section 07",
    title: "Contact Us",
    body: (
      <p>
        If you have any questions about these Terms, please contact us at{" "}
        <a
          href="mailto:legal@contentpilot.ai"
          className="text-link-blue hover:underline underline-offset-4"
        >
          legal@contentpilot.ai
        </a>
        .
      </p>
    ),
  },
];

export default function TermsClient() {
  return (
    <div className="min-h-screen bg-canvas-cream font-sans text-ink-black selection:bg-signal-orange selection:text-white">
      <Navbar />

      <main className="relative overflow-hidden pt-35 md:pt-50 pb-20 md:pb-30">
        <motion.div
          aria-hidden
          initial={{ opacity: 0 }}
          animate={{ opacity: 1, rotate: 360 }}
          transition={{
            opacity: { duration: 1.2 },
            rotate: { duration: 90, ease: "linear", repeat: Infinity },
          }}
          className="absolute right-[-20vw] top-[6vh] w-[55vw] h-[55vw] border border-light-signal-orange/25 rounded-full pointer-events-none"
        />
        <motion.div
          aria-hidden
          initial={{ opacity: 0 }}
          animate={{ opacity: 1, rotate: -360 }}
          transition={{
            opacity: { duration: 1.2, delay: 0.2 },
            rotate: { duration: 140, ease: "linear", repeat: Infinity },
          }}
          className="absolute right-[-14vw] top-[14vh] w-[42vw] h-[42vw] border border-light-signal-orange/20 rounded-full pointer-events-none"
        />
        <div
          aria-hidden
          className="absolute right-[-5vw] top-[20vh] w-[40vw] h-[40vw] bg-signal-orange/8 rounded-full blur-[120px] pointer-events-none"
        />
        <div
          aria-hidden
          className="absolute inset-0 opacity-[0.35] pointer-events-none"
          style={{
            backgroundImage:
              "radial-gradient(circle, rgba(15,15,15,0.08) 1px, transparent 1px)",
            backgroundSize: "28px 28px",
            maskImage: "linear-gradient(to bottom, black 0%, transparent 70%)",
            WebkitMaskImage:
              "linear-gradient(to bottom, black 0%, transparent 70%)",
          }}
        />

        <div className="px-6 md:px-25 max-w-5xl mx-auto relative z-10">
          <motion.div
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="mb-10"
          >
            <Link
              href="/auth/signup"
              className="inline-flex items-center gap-2 text-slate-gray hover:text-signal-orange transition-colors text-[14px] font-medium group"
            >
              <ArrowLeft
                size={16}
                className="group-hover:-translate-x-1 transition-transform"
              />
              <span>Back to Sign Up</span>
            </Link>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="eyebrow mb-8"
          >
            <span className="eyebrow-dot" />
            TERMS & CONDITIONS
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
              duration: 0.9,
              delay: 0.1,
              ease: [0.16, 1, 0.3, 1],
            }}
            className="text-[44px] sm:text-[64px] md:text-[84px] mb-8 tracking-mc-tight leading-[0.95] font-medium text-ink-black"
          >
            The{" "}
            <span className="relative inline-block">
              <span className="relative z-10 italic font-normal">rules</span>
              <motion.span
                initial={{ scaleX: 0 }}
                animate={{ scaleX: 1 }}
                transition={{ delay: 0.8, duration: 0.8 }}
                style={{ transformOrigin: "left" }}
                className="absolute bottom-[6%] left-0 right-0 h-1.5 md:h-2.5 bg-signal-orange/80 z-0 rounded-full"
              />
            </span>
            <br />
            of the flight deck.
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.8 }}
            className="text-slate-gray text-[17px] md:text-[20px] max-w-2xl leading-relaxed mb-8"
          >
            The agreement between you and ContentPilot when you use our
            AI-assisted SEO content platform.
          </motion.p>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5, duration: 0.6 }}
            className="inline-flex items-center gap-3 px-4 py-2 bg-white/70 backdrop-blur-sm border border-ink-black/5 rounded-mc-pill text-[12px] tracking-mc-wide uppercase text-slate-gray"
          >
            <span className="w-1.5 h-1.5 rounded-full bg-signal-orange" />
            Last updated: April 2026
          </motion.div>
        </div>
      </main>

      <section className="relative px-6 md:px-25 max-w-5xl mx-auto pb-25 md:pb-40">
        <div className="grid grid-cols-1 gap-4 md:gap-6">
          {sections.map((section, idx) => {
            const Icon = section.icon;
            return (
              <motion.article
                key={section.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{
                  duration: 0.7,
                  ease: [0.16, 1, 0.3, 1],
                  delay: idx * 0.05,
                }}
                className="group relative bg-white rounded-mc-consent border border-ink-black/5 shadow-mc-soft hover:shadow-mc-heavy transition-shadow duration-500 p-8 md:p-12 overflow-hidden"
              >
                <div
                  aria-hidden
                  className="absolute -top-16 -right-16 w-40 h-40 rounded-full bg-canvas-cream transition-transform duration-700 group-hover:scale-125 pointer-events-none"
                />
                <span
                  aria-hidden
                  className="absolute bottom-4 right-6 md:bottom-6 md:right-10 text-[90px] md:text-[120px] font-medium leading-none tracking-mc-tight text-ink-black/4 select-none"
                >
                  {String(idx + 1).padStart(2, "0")}
                </span>

                <div className="relative z-10 flex flex-col md:flex-row gap-8 md:gap-10">
                  <div className="shrink-0">
                    <div className="relative w-14 h-14 md:w-16 md:h-16">
                      <span
                        aria-hidden
                        className="absolute inset-0 rounded-full bg-signal-orange/10 blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                      />
                      <div className="relative w-full h-full bg-canvas-cream rounded-full flex items-center justify-center border border-ink-black/5 shadow-sm">
                        <Icon
                          className="w-6 h-6 md:w-7 md:h-7 text-signal-orange"
                          strokeWidth={1.75}
                        />
                      </div>
                    </div>
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-5">
                      <span className="text-[11px] font-bold tracking-mc-wide text-signal-orange uppercase">
                        {section.tag}
                      </span>
                      <span className="flex-1 h-px bg-ink-black/10" />
                    </div>

                    <h2 className="text-[24px] md:text-[30px] font-medium tracking-mc-tight text-ink-black leading-tight mb-5">
                      {section.title}
                    </h2>

                    <div className="text-slate-gray text-[15px] md:text-[17px] leading-relaxed">
                      {section.body}
                    </div>
                  </div>
                </div>
              </motion.article>
            );
          })}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="mt-12 md:mt-16 pt-8 border-t border-ink-black/10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
        >
          <p className="text-slate-gray text-[14px]">
            Need to review how we handle data? See our Privacy Policy.
          </p>
          <Link
            href="/privacy"
            className="inline-flex items-center gap-2 text-[14px] font-medium text-ink-black hover:text-signal-orange transition-colors"
          >
            Read our Privacy Policy
            <span aria-hidden>→</span>
          </Link>
        </motion.div>
      </section>

      <Footer />
    </div>
  );
}
